spring:
  data:
    mongodb:
      database: projectWDT #wdt_project
      uri: mongodb+srv://mongo1:projectWTD@cluster0.x1xtc.mongodb.net/projectWTD

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors:
      allowed-origins: true
      allow-credentials: true
  tools:
    schema-location-pattern: "**/*.graphqls"

graphiql:
  enabled: true
  mapping: /graphiql

server:
  port : 8080