spring:
  data:
    mongodb:
      uri: mongodb+srv://mongo1:projectWTD@cluster0.x1xtc.mongodb.net
      database: projectWTD
      #port: 27017
  application:
    name: projects-service

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors:
      allowed-origins: true
      allow-credentials: true
  tools:
    schema-location-pattern: "**/*.graphqls"

graphiql:
  enabled: true
  mapping: /graphiql

server:
  port : 9090