spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
      #host: localhost
      #port: 27017
  application:
    name: projects-service

graphql:
  servlet:
    enabled: true
    mapping: /projects
    cors:
      allowed-origins: true
      allow-credentials: true
  tools:
    schema-location-pattern: "**/*.graphqls"

graphiql:
  enabled: true
  mapping: /graphiql-projects
  endpoint:
    graphql: /projects

server:
  port : 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/