spring:
  data:
    mongodb:
      uri: mongodb+srv://mongo1:projectWTD@cluster0.x1xtc.mongodb.net
      database: projectWTD
      #host: localhost
      #port: 27017
  application:
    name: users-service

graphql:
  servlet:
    enabled: true
    mapping: /users
    cors:
      allowed-origins: true
      allow-credentials: true
  tools:
    schema-location-pattern: "**/*.graphqls"

graphiql:
  enabled: true
  mapping: /graphiql

server:
  port : 8070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/